on:
  [pull_request]

name: Check

jobs:
  check:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::593043004533:role/github_role
          role-session-name: MySessionName
