name: gh-creds
on:
  push:

env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: arn:aws:iam::593043004533:role/github_role
  WORK_DIR: 'aws/terraform'
jobs:
  get-caller-identity:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - run: aws sts get-caller-identity
